# Generated by Django 4.1.7 on 2023-02-16 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Firma Adı')),
                ('company_description', models.TextField(max_length=500, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='İsim Soyisim')),
                ('image', models.ImageField(upload_to='')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefon Numarası')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.company', verbose_name='Firma')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Açıklma')),
                ('choices_call_type', models.CharField(choices=[('gelen', 'gelen'), ('giden', 'giden')], max_length=5, verbose_name='Arama Türü')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.person', verbose_name='İsim Soyisim')),
            ],
        ),
    ]
