# Generated by Django 4.1.7 on 2023-02-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='companies', verbose_name='Şirket Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='persons', verbose_name='Profil Fotoğrafı'),
        ),
    ]
